### ISSUE TITLE
tracking create-react-app

### ISSUE THREAD

**Issue by talkingtab** [DimiMikadze/create-react-library#2]
I'd like to track create-react-app as far as possible. Is there a chance of getting some diff script and or a set of additional files, for example 
- add the line to config/paths.js
- add 'buildlib' to the scripts in package.json
- add buildlib.js to scripts/
- etc

I tried to diff all the files from cloning this project  against those from a project generated by  create-react-app, but it wasn't clear to me whether the differences were because of different versions of create-react-app or changes that were required to generate a component.

Thanks much for doing this!

**Comment by DimiMikadze** [comment]
HI @talkingtab thanks for your feedback!

I'd love to track create-react-app also, we'll do similar thing in the following week ( this week is too busy :) ) and let you know!

**Comment by MerlinScheurer** [comment]
Reminder :wink: 

A step by step update guide would be nice. ( So, that i am able to use the latest cra version to build the library )
or at least a list of changes that were made to transform cra to crl.

**Comment by DimiMikadze** [comment]
@talkingtab @Metin200 hey, sorry for delay... We are launching our website where this subject will be available as a blog post and video tutorial, please give us roughly two weeks

**Comment by DimiMikadze** [comment]
Hi guys, sorry for being very very late! :)

We have decided to track `create-react-app` constantly so our repository will be always updated with new versions of `create-react-app`

I can't go to details like what part we have changed/added to particular files, because there are plenty of them and it's being changed with almost every new version of `CRA`, but i can write files list and general changes what we did.

- package.json ( moved dependencies to devDependencies, added NPM library specific blocks )
- config/paths.js ( updated and added new paths for library )
- config/webpack-config.prod.js ( added new blocks for supporting NPM library, updated old paths and configs )
- scripts/build.js ( same as above )
- .gitignore ( removed build folder )
- src ( I guess changes in this folder are pretty much self explanatory )

I'm closing this issue right now, but please feel free to re open it, if needed.

**Comment by talkingtab** [comment]
Great! Thanks.
