### ISSUE TITLE
not supporting async await

### ISSUE THREAD

**Issue by theone3nu** [DimiMikadze/create-react-library#20]
Its not supporting async await just like crate react app does. Please add this feature. I am getting Uncaught ReferenceError: regeneratorRuntime is not defined when i use async keyword.

**Comment by DimiMikadze** [comment]
Hi @theone3nu 

We have removed all the polyfills by default, because it was  increasing very much size of the production build file and most of the libraries don't require features like fetch or async await.

So what you have to do is, to load specific polyfill either in webpack configuration or inside libraries file.
