### ISSUE TITLE
Combine efforts with create-react-library CLI?

### ISSUE THREAD

**Issue by transitive-bullshit** [DimiMikadze/create-react-library#27]
Hey @DimitriMikadze, I recently published a super simple CLI called [create-react-library](https://www.npmjs.com/package/create-react-library) for bootstrapping new react libraries based on rollup and create-react-app.

I wasn't aware of this repo at the time lol.  Any interest in combining our efforts?

I was thinking it'd be useful to have multiple templates in the CLI like if you wanted to use this repo's webpack setup instead of the default rollup config.

Lemme know && thanks!

**Comment by DimiMikadze** [comment]
Hi @transitive-bullshit 

Sure, i just see we have taken totally different approaches taken, do you have any idea how we can combine them?

**Comment by transitive-bullshit** [comment]
Hey yeah, I think my response in the other thread definitely came off wrong.  I'd love to join forces if we can figure it out!

Here's what I'm thinking:

- I already have the create-react-library npm module and binary, which makes it easier to get started, but your boilerplate is really popular.
- Maybe we could add an option during the CLI creation to choose between webpack vs rollup and use one or the other boilerplate accordingly under the hood?
- I'm thinking once the user makes this choice once, it would be the default for them from then on by storing some user config state.

The one area I'm concerned with is keeping the template used in the CLI in sync with the boilerplate repo itself.  I haven't figured out a clean way to do this yet with my original [boilerplate](https://github.com/transitive-bullshit/react-modern-library-boilerplate), so if you have any ideas here, I'd love to hear them.

Thoughts?

**Comment by DimiMikadze** [comment]
@transitive-bullshit i would also love combining our efforts and i'm not into Webpack vs Rollup, by `we have taken totally different approaches`, i mean that you have built configuration of build tools by your own and i'm using exactly same configuration files, that `CRA` uses slightly edited.

Philosophy of this project is that to create `React library` using `create react app`, therefore if we'll add support for Rollup, that means we have to build all this configuration from scratch, because `CRA` uses Webpack for bundling scripts.

Because of this reason it's hard for me to see how we can merge this two libraries, but if you have idea how we can merge them without loosing their philosophy,  (`Using Rollup in your case` and `create library with CRA in my case`) i'm totally into it.
