### ISSUE TITLE
React Hooks don't work

### ISSUE THREAD

**Issue by felixrigau** [DimiMikadze/create-react-library#55]
I'm trying to create and export a React component using useState() React hook, but the example application that imports the exported component by the library doesn't work.

![react hooks](https://user-images.githubusercontent.com/33104535/57619419-2c407500-7586-11e9-913c-8b87b63db69d.png)

I just generated the project using the default settings, so the _package.json_ files and the _rollup.config.js_ were generated by "create-react-library" **(none modifications)**.

I've created this small component as an example:

```
import React, { useState } from 'react';

function SimpleComponent(){
    const [counter, setcounter] = useState(0)
    return (
        <div onClick={() => setcounter(counter => counter + 1)}>
            {counter}
        </div>
    )
}
```

Any idea how to fix it?
Thanks!

**Comment by DimiMikadze** [comment]
@felixrigau you're opening an issue in a different repository, we are not using rollup.

**Comment by dwilt** [comment]
I'm also running into this as well. I created a component, imported it into another project via `yarn link` and am seeing this.

**Comment by dwilt** [comment]
I believe this is because this starter kit is not handling multiple versions of React correctly. I have a component that is working (with hooks) inside of my library repo but I get this error when I use it inside of another project (built with create react app). I'm pretty sure there is some config/dependency issue with webpack
