### ISSUE TITLE
Update more frequently .

### ISSUE THREAD

**Issue by ivanjeremic** [DimiMikadze/create-react-library#61]
I tried now a few packages like this one and this is the only one that worked right away for men, No I hope this project stays active and get some nice updates because it's really nice for now to work with it.

**Comment by panz3r** [comment]
Hi @ivanjeremic ,

I also think this repo is a great starting point to create awesome react libraries (I'm using it for some of my projects too).

I just submitted a PR (#63) to update it to the latest available version of `create-react-app` (currently `v3.1.2`).

I'm also writing a guide on how to upgrade a project using `create-react-library` as a starting point and also how to upgrade `create-react-library` itself, hoping that the process will be easier for everyone to do (other than me - this is my second PR to upgrade this project 😬 ).

**Comment by DimiMikadze** [comment]
Hi thank you guys for your contribution and big thank you @panz3r for your regular pull requests regarding updating the project :) I'm thinking to write cli tool for this repo, so instead of cloning and manually installing dependencies, users could install it with one command `npx create-react-library my-lib`, same as Create React App. I'm in the process of searching suitable NPM package name right now.

**Comment by panz3r** [comment]
Hi @DimiMikadze ,

I was thinking the same. It would be great if it could become exactly like `create-react-app` and keeping the name `create-react-library` would be huge since it allows a user to `yarn create react-library`.

Looking at how `create-react-app` works I have an idea on how it could be done, I’ll try to find some time in the following days and maybe open a `PR`.

**Comment by DimiMikadze** [comment]
@panz3r I know how to implement it, i've created similar project https://github.com/udilia/create-social-network

Just the name `create-react-library` and `create-react-lib` is already taken. I have registered `create-react-libs` couldn't think anything better than that, that is not taken 😬

**Comment by DimiMikadze** [comment]
Hi @ivanjeremic @panz3r i've added cli tool for installing the project and moved it to my organizations profile, so now users can install it via `npx @udilia/create-react-library my-lib`. Let me know if you encounter any problems 👍
